name: flutter_record
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  pigeon: ^14.0.0
  build_runner: ^2.3.3

flutter:
  plugin:
    platforms:
      android:
        package: com.xhhold.flutter_record
        pluginClass: FlutterRecordPlugin